name: CI devops 2024 test
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: [ origin, dev, main ]
  pull_request:

jobs:
  # Use the docker.yml file and the backend_test.yml file to do the CI/CD
  back_end_tests:
    uses: ./.github/workflows/backend_test.yml
    with:
      project_key: 'jiaenliu42_jiaen-liu-test'
      organization: 'jiaenliu42'
      pom_path: './simple-api/pom.xml'
    secrets:
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
